export const onboardingGuideSteps = [
  {
    id: "dashboard-video",
    routeName: "dashboard",
    selector: '[data-guide="dashboard.video"]',
    title: "实时检测画面",
    description: "这里显示当前接入的数据源画面，并叠加检测框和识别结果。",
    usage: "先在右侧切换数据源，再回到这里观察模型输出。",
  },
  {
    id: "dashboard-stream",
    routeName: "dashboard",
    selector: '[data-guide="dashboard.stream"]',
    title: "视频流切换",
    description: "用于切换实时流、本地视频、本地图片三种输入方式。",
    usage: "按需求选择模式并填写地址或上传文件，随后启动检测。",
  },
  {
    id: "dashboard-quick-new-task",
    routeName: "dashboard",
    selector: '[data-guide="dashboard.quick-new-task"]',
    title: "快速操作 - 新建任务",
    description: "这个按钮会创建当前任务，并写入任务摘要供后续检测使用。",
    usage: "每次开始任务前都要先点“新建任务”，再进行实时流/视频/图片检测。",
  },
  {
    id: "dashboard-quick-upload-txt",
    routeName: "dashboard",
    selector: '[data-guide="dashboard.quick-upload-txt"]',
    title: "快速操作 - 上传TXT",
    description: "该按钮用于上传图片检测参考的 TXT 文件。",
    usage: "每次做图片检测前都要先上传 TXT 文件，再点击“开始图片检测”。",
  },
  {
    id: "dashboard-map",
    routeName: "dashboard",
    selector: '[data-guide="dashboard.map"]',
    title: "目标定位地图",
    description: "地图面板展示位置信息与航向，便于定位目标区域。",
    usage: "可调整经纬度和航向参数，用于校验目标位置映射。",
  },
  {
    id: "dashboard-control",
    routeName: "dashboard",
    selector: '[data-guide="dashboard.control"]',
    title: "系统控制",
    description: "控制检测启停，并可快速调整置信度和 IoU 阈值。",
    usage: "先调参数，再开启检测，可快速观察识别效果变化。",
  },
  {
    id: "dashboard-result",
    routeName: "dashboard",
    selector: '[data-guide="dashboard.result"]',
    title: "实时检测结果",
    description: "列表展示每条检测记录的时间、类别、置信度和坐标。",
    usage: "用于追踪识别质量，并与视频画面结果进行核对。",
  },
  {
    id: "metrics-overview",
    routeName: "metrics",
    selector: '[data-guide="metrics.overview"]',
    title: "核心指标总览",
    description: "集中展示模型实时指标、累计统计和运行状态信息。",
    usage: "定期刷新并查看关键指标，评估模型稳定性。",
  },
  {
    id: "metrics-refresh",
    routeName: "metrics",
    selector: '[data-guide="metrics.refresh"]',
    title: "指标刷新",
    description: "点击后重新拉取指标数据并更新图表。",
    usage: "在切换任务或参数后刷新，确认最新分析结果。",
  },
  {
    id: "tasks-create",
    routeName: "tasks",
    selector: '[data-guide="tasks.create"]',
    title: "新建任务",
    description: "从这里新增检测任务，设置任务名称、场景和输入源。",
    usage: "建议按场景创建任务，便于后续回看和对比结果。",
  },
  {
    id: "tasks-search",
    routeName: "tasks",
    selector: '[data-guide="tasks.search"]',
    title: "任务搜索",
    description: "支持按任务 ID、名称、类型和来源快速筛选。",
    usage: "输入关键词后立即筛选，可快速定位历史任务。",
  },
  {
    id: "tasks-table",
    routeName: "tasks",
    selector: '[data-guide="tasks.table"]',
    title: "历史任务列表",
    description: "展示任务详情、状态和操作入口（查看详情/删除）。",
    usage: "点击某一行可切换当前任务，结合分页管理大批量记录。",
  },
  {
    id: "settings-nav",
    routeName: "settings",
    selector: '[data-guide="settings.nav"]',
    title: "设置导航",
    description: "左侧导航用于切换检测、偏好、安全和高级设置模块。",
    usage: "按分类逐项调整，避免集中修改导致配置混乱。",
  },
  {
    id: "settings-backend-api",
    routeName: "settings",
    selector: '[data-guide="settings.backend-api"]',
    title: "后端 API 地址",
    description: "配置后端服务地址，影响全站接口请求目标。",
    usage: "填写 IP:端口 后保存，网络或服务变更时优先更新此处。",
  },
  {
    id: "app-theme-toggle",
    routeName: "settings",
    selector: '[data-guide="app.theme-toggle"]',
    title: "主题切换",
    description: "用于切换浅色/深色界面主题。",
    usage: "根据现场光照环境选择更舒适的视觉模式。",
  },
  {
    id: "app-logout",
    routeName: "settings",
    selector: '[data-guide="app.logout"]',
    title: "退出登录",
    description: "当前账号的安全退出入口。",
    usage: "演示结束或更换账号时请从这里退出登录。",
  },
  {
    id: "app-ai-assistant-fab",
    routeName: "settings",
    selector: '[data-guide="app.ai-assistant-fab"]',
    title: "小智 AI 助手",
    description: "本小智就在这里哦，点我就能随时问系统状态、检测结果和参数建议。",
    usage: "卡住时来找我就对啦，我会像贴身小搭子一样陪你把流程跑顺。",
  },
];
